const data = {
  products: [
    {
      _id: "1",
      name: "Iphone 11 Pro Max Case",
      category: "Case",
      image: "/assets/case1.jpg",
      price: 10.5,
      countInStock: 10,
      brand: "Beep-Line",
      keywords: ["rugged case"],
      rating: 4.5,
      numReviews: 10,
      description:
        "Keep your iPhone 11 Pro Max safe with this beautiful case. Colours white and red.",
    },
    {
      _id: "2",
      name: "Iphone 11 Pro Case",
      category: "Case",
      image: "/assets/case2.jpg",
      price: 10,
      countInStock: 20,
      brand: "Smart Case",
      keywords: ["thin case"],
      rating: 3.0,
      numReviews: 10,
      description:
        "Keep your iPhone 11 Pro safe with this beautiful case. Colors white, red and blue.",
    },
    {
      _id: "3",
      name: "Iphone 8 Case",
      category: "Case",
      image: "/assets/case3.jpg",
      price: 10,
      countInStock: 20,
      brand: "Clear Case",
      keywords: ["clear case", "transparent"],
      rating: 2.0,
      numReviews: 10,
      description:
        "Keep your iPhone 8 safe with this beautiful case. Fits standard iPhone 8. Colours white, red and blue.",
    },
    {
      _id: "4",
      name: "OnePlus 5T Screen Protector",
      category: "Screen Protector",
      image: "/assets/screen1.jpg",
      price: 6.5,
      countInStock: 20,
      brand: "Beep-Line",
      keywords: ["TPU", "no scratches"],
      rating: 5.0,
      numReviews: 10,
      description:
        "Add some extra protection to your phone. If anything happens you don't need to worry. Fits OnePlus 5t screen.",
    },
    {
      _id: "5",
      name: "Samsung S8 Screen Protector",
      category: "Screen Protector",
      image: "/assets/screen2.jpg",
      price: 6.5,
      countInStock: 20,
      brand: "Unbranded",
      keywords: ["Tempered glass"],
      rating: 5.0,
      numReviews: 10,
      description:
        "Worried about expensive and curvy screen in your samsung? This is screen protector to your Galaxy Samsung S8.",
    },
    {
      _id: "6",
      name: "Iphone SE Screen Protector",
      category: "Screen Protector",
      image: "/assets/screen3.jpg",
      price: 5.5,
      countInStock: 20,
      brand: "Unbranded",
      keywords: ["PET"],
      rating: 2.0,
      numReviews: 10,
      description: "Keep your iPhone's SE screen fall resistant.",
    },
    {
      _id: "7",
      name: "Universal phone holder",
      category: "Phone Holders",
      image: "/assets/holder1.jpg",
      price: 12,
      countInStock: 20,
      brand: "Unbranded",
      keywords: ["suction cup"],
      rating: 4.0,
      numReviews: 10,
      description: "It fits all phones between 4' and 6.5'.",
    },
    {
      _id: "8",
      name: "Long arm holder",
      category: "Phone Holders",
      image: "/assets/holder2.jpg",
      price: 11.5,
      countInStock: 20,
      brand: "Beep-Line",
      keywords: ["suction cup"],
      rating: 4.0,
      numReviews: 10,
      description:
        "This holder with long arm can be used at home or your car as well.",
    },
    {
      _id: "9",
      name: "Multi-port Powerbank Amber",
      category: "Power Banks",
      image: "/assets/bank1.jpg",
      price: 22.5,
      countInStock: 20,
      brand: "Beep-Line",
      keywords: ["multi-port"],
      rating: 4.0,
      numReviews: 10,
      description:
        "Amber provides you 15000mAh for your daily mobile life. Amber is nicely designed with soft touch finish surface. Dual USB-A output ports that can charge 2 devices at once, or share it with friends.",
    },
    {
      _id: "10",
      name: "Big Capacity Curtis Power Bank",
      category: "Power Banks",
      image: "/assets/bank2.jpg",
      price: 7.5,
      countInStock: 0,
      brand: "Unbranded",
      keywords: ["big capacity"],
      rating: 4.0,
      numReviews: 10,
      description:
        "This charger has got 26800mAh capacity. You can charge your phone even 8 times. Excelent for long travels.",
    },
    {
      _id: "11",
      name: "Nylon Charging Cable Micro-USB",
      category: "Cables",
      image: "/assets/cable1.jpg",
      price: 15,
      countInStock: 10,
      brand: "Unbranded",
      keywords: ["nylon"],
      rating: 4.0,
      numReviews: 10,
      description:
        "This replacement Micro-USB Data Cable in provides high-speed data transfer rates, while simultaneously charging your Micro-USB compatible phone through your computer's USB port.",
    },
    {
      _id: "12",
      name: "Nomad Kevlar Lightning Cable",
      category: "Cables",
      image: "/assets/cable2.jpg",
      price: 15,
      countInStock: 10,
      brand: "Unbranded",
      keywords: ["kevlar"],
      rating: 4.0,
      numReviews: 10,
      description:
        "The entire Nomad collection of Lightning cables feature DuPont Kevlar K-29, both in the braiding and the inner core of the cable. The end result is a Lightning cable that boasts not only impressive durability but heat resistance and high tensile strength too.",
    },
    {
      _id: "13",
      name: "Juice Lightning Wall Charger",
      category: "Chargers",
      image: "/assets/charger1.jpg",
      price: 19.5,
      countInStock: 10,
      brand: "Unbranded",
      keywords: ["iphone chargers"],
      rating: 4.5,
      numReviews: 10,
      description:
        "The Juice Apple Lightning mains charger provides power for your Apple Lightning devices. Included is a mains charger with integrated 1.5m Apple Lightning cable. Plus a handy carry bag to keep your charger tidy when not in use.",
    },
    {
      _id: "14",
      name: "Belkin 10W Qi Wireless",
      category: "Chargers",
      image: "/assets/wicharger2.jpg",
      price: 19.5,
      countInStock: 10,
      brand: "Belkin",
      keywords: ["wireless chargers"],
      rating: 4.5,
      numReviews: 10,
      description:
        "Belkin 10W Qi Wireless Charger Pad with QC3 Plug - Black. Fast wireless charging up to 10 watts so you always safely get the fastest possible wireless charge. Just lay your phone onto the pad for a quick and easy power boost. Fast wireless charging for Qi-enabled devices up to 10W.",
    },
    {
      _id: "15",
      name: "USB-C Mains Charger",
      category: "Chargers",
      image: "/assets/charger3.jpg",
      price: 8,
      countInStock: 10,
      brand: "Unbranded",
      keywords: ["USB-C chargers"],
      rating: 4.5,
      numReviews: 10,
      description:
        "Keep your micro USB devices charged up and ready to use with this micro USB and mains charger. The USB socket on the mains is handy if you live with people that have different devices, if you fancy sharing.",
    },
  ],
};
export default data;
